name: ğŸ§° Devenv

on:
  push:
    branches: [main, release]
  pull_request:
    branches: [main]

jobs:
  test:
    name: ğŸ§ª Devenv Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: â„ï¸ Install Nix
        uses: cachix/install-nix-action@v30
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: ğŸ“¦ Set up Cachix
        uses: cachix/cachix-action@v15
        with:
          name: devenv

      - name: ğŸ”§ Install devenv
        run: nix profile install nixpkgs#devenv

      - name: âœ… Run devenv test
        run: devenv test
